image: mono:latest

stages:
    - build
    - test

variables:
    solution: "Astra.sln"
    test: "Astra.Test"

build:
    stage: build
    script:
        - msbuild Astra.sln /t:Rebuild /p:Configuration=Release /p:Platform="x86" /m