stages:
    - build

variables:
    msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
    solution: "Astra.sln"

build_windows:
    stage: build
    script:
        - '& "$msbuild" "$solution" /t:Rebuild /p:Configuration=Release /p:Platform="Win32" /m'
    tags:
        - windows