image: mono:latest

stages:
    - build
    - test

variables:
    msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
    solution: "Astra.sln"
    test: "Astra.Test"

build_windows:
    stage: build
    script:
        - '& "$msbuild" -help'
    tags:
        - shared-windows
        - windows
        - windows-1809